# --- Original file content below ---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/arewm/devcontainer-playground?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: devcontainer-playground
    appstudio.openshift.io/component: devcontainer-playground
    pipelines.appstudio.openshift.io/type: build
  name: devcontainer-playground-on-pull-request
  namespace: arewm-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/arewm/devcontainer-playground:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: .devcontainer/Containerfile
  - name: skip-checks
    value: "true"
  - name: build-image-index
    value: "false"
  - name: artifact-version # Added to pass dynamic version for PRs
    # Uses PaC variable for target_branch and appends '-pr'.
    # Alternatively, if {{target_branch}} is always 'main' for PRs,
    # you might prefer '{{source_branch}}-pr' or 'pr-{{pull_request_number}}'.
    value: '{{target_branch}}-pr'
  # ------------------------------------------------------------------------------------
  # The following parameters are commented out because their values in this PipelineRun
  # would be identical to the default values defined in the referenced Pipeline
  # (in .tekton/build-pipeline.yaml). They can be uncommented and modified if specific
  # overrides are needed for this PipelineRun.
  # ------------------------------------------------------------------------------------
  # - name: build-platforms # Pipeline default: [- linux/x86_64]
  #   value:
  #   - linux/x86_64
  # - name: path-context # Pipeline default: "."
  #   value: "."
  # - name: hermetic # Pipeline default: "false"
  #   value: "false"
  # - name: prefetch-input # Pipeline default: ""
  #   value: ""
  # - name: build-source-image # Pipeline default: "false"
  #   value: "false"
  # - name: build-args # Pipeline default: []
  #   value: []
  # - name: rebuild # Pipeline default: "false"
  #   value: "false"
  # - name: build-args-file # Pipeline default: ""
  #   value: ""
  # - name: privileged-nested # Pipeline default: "false"
  #   value: "false"

  pipelineRef:
    name: build-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-devcontainer-playground
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
