# --- Original file content below ---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/arewm/devcontainer-playground?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: devcontainer-playground
    appstudio.openshift.io/component: devcontainer-playground
    pipelines.appstudio.openshift.io/type: build
  name: devcontainer-playground-on-pull-request
  namespace: arewm-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/arewm/devcontainer-playground:on-pr-{{revision}}
  - name: image-expires-after # Value '5d' is different from pipeline default '""'. Kept.
    value: 5d
  - name: dockerfile # Value '.devcontainer/Containerfile' is different from pipeline default 'Dockerfile'. Kept.
    value: .devcontainer/Containerfile
  - name: skip-checks # Value '"true"' is different from pipeline default '"false"'. Kept.
    value: "true"
  - name: build-image-index # Value '"false"' is different from pipeline default '"true"'. Kept.
    value: "false"
  # ------------------------------------------------------------------------------------
  # The following parameters are commented out because their values in this PipelineRun
  # would be identical to the default values defined in the referenced Pipeline
  # (in .tekton/build-pipeline.yaml). They can be uncommented and modified if specific
  # overrides are needed for this PipelineRun.
  # ------------------------------------------------------------------------------------
  # - name: build-platforms # Pipeline default: [- linux/x86_64]
  #   value:
  #   - linux/x86_64
  # - name: path-context # Pipeline default: "."
  #   value: "."
  # - name: hermetic # Pipeline default: "false"
  #   value: "false"
  # - name: prefetch-input # Pipeline default: ""
  #   value: ""
  # - name: build-source-image # Pipeline default: "false"
  #   value: "false"
  # - name: build-args # Pipeline default: []
  #   value: []
  # - name: rebuild # Pipeline default: "false"
  #   value: "false"
  # - name: build-args-file # Pipeline default: ""
  #   value: ""
  # - name: privileged-nested # Pipeline default: "false"
  #   value: "false"
  # Note: Ensure all other required parameters from the pipeline definition that do not have defaults
  # are explicitly provided if not injected by Konflux/Pipelines-as-Code.

  pipelineRef:
    name: build-pipeline # MODIFIED from docker-build-multi-platform-oci-ta
  taskRunTemplate:
    serviceAccountName: build-pipeline-devcontainer-playground
  workspaces:
  - name: git-auth # This is an optional workspace in the Pipeline definition
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
