# --- Original file content below ---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/arewm/devcontainer-playground?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: devcontainer-playground
    appstudio.openshift.io/component: devcontainer-playground
    pipelines.appstudio.openshift.io/type: build
  name: devcontainer-playground-on-push
  namespace: arewm-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/arewm/devcontainer-playground:{{revision}}
  # - name: build-platforms # Commented out: Value '[- linux/x86_64]' matches pipeline default.
  #   value:
  #   - linux/x86_64
  - name: dockerfile
    value: .devcontainer/Containerfile
  - name: artifact-version # Added to pass dynamic version to the pipeline
    value: '{{target_branch}}' # Uses PaC variable for the target branch name
  pipelineRef:
    name: build-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-devcontainer-playground
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
